-- return {
-- 	"yetone/avante.nvim",
-- 	event = "VeryLazy",
-- 	lazy = false,
-- 	version = false,
-- 	opts = {
-- 		provider = "ollama",
-- 		auto_suggestions_provider = "ollama",
-- 		providers = {
-- 			ollama = {
-- 				endpoint = "http://127.0.0.1:11434",
-- 				model = "qwen2.5-coder:3b",
-- 				extra_request_body = {
-- 					options = {
-- 						num_ctx = 4096,
-- 					},
-- 				},
-- 			},
-- 			-- claude = {
-- 			-- 	endpoint = "https://api.anthropic.com",
-- 			-- 	model = "claude-sonnet-4-20250514",
-- 			-- 	temperature = 0,
-- 			-- 	max_tokens = 4096,
-- 			-- 	api_key_name = "ANTHROPIC_API_KEY",
-- 			-- },
-- 		},
-- 		behaviour = {
-- 			auto_suggestions = true, -- Experimental stage
-- 			auto_set_highlight_group = true,
-- 			auto_set_keymaps = true,
-- 			auto_apply_diff_after_generation = false,
-- 			support_paste_from_clipboard = false,
-- 		},
-- 		mappings = {
-- 			--- @class AvanteConflictMappings
-- 			diff = {
-- 				ours = "co",
-- 				theirs = "ct",
-- 				all_theirs = "ca",
-- 				both = "cb",
-- 				cursor = "cc",
-- 				next = "]x",
-- 				prev = "[x",
-- 			},
-- 			suggestion = {
-- 				accept = "<M-l>",
-- 				next = "<M-]>",
-- 				prev = "<M-[>",
-- 				dismiss = "<C-]>",
-- 			},
-- 			jump = {
-- 				next = "]]",
-- 				prev = "[[",
-- 			},
-- 			submit = {
-- 				normal = "<CR>",
-- 				insert = "<C-s>",
-- 			},
-- 			sidebar = {
-- 				apply_all = "A",
-- 				apply_cursor = "a",
-- 				switch_windows = "<Tab>",
-- 				reverse_switch_windows = "<S-Tab>",
-- 			},
-- 		},
-- 		hints = { enabled = true },
-- 		windows = {
-- 			position = "right", -- the position of the sidebar
-- 			wrap = true, -- similar to vim.o.wrap
-- 			width = 30, -- default % based on available width
-- 			sidebar_header = {
-- 				align = "center", -- left, center, right for title
-- 				rounded = true,
-- 			},
-- 		},
-- 		highlights = {
-- 			---@type AvanteConflictHighlights
-- 			diff = {
-- 				current = "DiffText",
-- 				incoming = "DiffAdd",
-- 			},
-- 		},
-- 		--- @class AvanteConflictUserConfig
-- 		diff = {
-- 			autojump = true,
-- 			---@type string | fun(): string
-- 			list_opener = "copen",
-- 		},
-- 	},
-- 	-- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
-- 	build = "make",
-- 	dependencies = {
-- 		"stevearc/dressing.nvim",
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		--- The below dependencies are optional,
-- 		"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
-- 		{
-- 			-- support for image pasting
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = {
-- 						insert_mode = true,
-- 					},
-- 				},
-- 			},
-- 		},
-- 		{
-- 			-- Make sure to set this up properly if you have lazy=true
-- 			'MeanderingProgrammer/render-markdown.nvim',
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 			},
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }
